# Generated by Django 3.2.8 on 2022-01-24 16:29

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='خبر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(null=True, upload_to=news.models.news_image_path, verbose_name='تصویر')),
                ('persiandate', models.CharField(max_length=20, verbose_name='تاریخ فارسی')),
                ('persiantime', models.CharField(max_length=20, verbose_name='ساعت فارسی')),
                ('source', models.CharField(max_length=50, verbose_name='منبع خبر')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اخبار',
                'verbose_name_plural': 'اخبار ها',
            },
        ),
    ]
