# Generated by Django 3.2.8 on 2022-01-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemodel',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='exchangemodel',
            name='rank',
            field=models.IntegerField(verbose_name='رتبه'),
        ),
        migrations.AlterField(
            model_name='exchangemodel',
            name='site',
            field=models.CharField(max_length=100, verbose_name='سابت'),
        ),
        migrations.AlterField(
            model_name='exchangemodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
    ]
