# Generated by Django 3.2.8 on 2022-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishname', models.CharField(max_length=100, verbose_name='نام ارز انگلیسی')),
                ('persianame', models.CharField(max_length=100, verbose_name='نام ارز فارسی')),
                ('coinnumber', models.CharField(max_length=100, verbose_name='تعداد ارز')),
                ('sender', models.CharField(max_length=100, verbose_name='فرستنده')),
                ('reciver', models.CharField(max_length=100, verbose_name='گیرنده')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خرید نهنگ',
                'verbose_name_plural': 'خرید نهنگ ها',
            },
        ),
    ]
