# Generated by Django 3.2.8 on 2022-01-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220119_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslevelgroup',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='useraccesslevelgroup',
            name='access_level_group',
        ),
        migrations.RemoveField(
            model_name='useraccesslevelgroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccessLevel',
        ),
        migrations.DeleteModel(
            name='AccessLevelGroup',
        ),
        migrations.DeleteModel(
            name='UserAccessLevelGroup',
        ),
    ]
